"""Generate frontend/src/filetypes.js from backend/filetypes.py.

backend/filetypes.py is the source of truth for the file-type taxonomy; this
script mirrors it into a plain-JS global (FP_FILETYPES) so the frontend
(no build step, no bundler) can classify extensions without duplicating the
list by hand. Run after any change to backend/filetypes.py --
tests/test_filetypes.py::test_generated_js_is_current fails otherwise.

Usage:
    py -3 scripts/build_filetypes.py [output-path]

Default output: <repo>/frontend/src/filetypes.js
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from backend import filetypes as ft

TEMPLATE = """// GENERATED by scripts/build_filetypes.py from backend/filetypes.py — do not edit.
const FP_FILETYPES = {data};
const _FP_EXT_TO_FAMILY = (() => {{ const m = {{}}; for (const [fam, exts] of Object.entries(FP_FILETYPES.families)) for (const e of exts) m[e] = fam; return m; }})();
const _FP_FAMILY_TO_GROUP = (() => {{ const m = {{}}; for (const [g, fams] of Object.entries(FP_FILETYPES.groups)) for (const f of fams) m[f] = g; return m; }})();
function fpFamilyFor(ext) {{ const e = String(ext || '').replace(/^\\./, '').toLowerCase(); return _FP_EXT_TO_FAMILY[e] || 'generic'; }}
function fpTypeGroupFor(ext, isDir) {{ if (isDir) return 'folder'; return _FP_FAMILY_TO_GROUP[fpFamilyFor(ext)] || 'other'; }}
function fpIsMedia(ext) {{ const g = fpTypeGroupFor(ext, false); return g === 'image' || g === 'video'; }}
"""


def render() -> str:
    data = json.dumps(ft.as_json(), indent=None, separators=(", ", ": "))
    return TEMPLATE.format(data=data)


def main() -> None:
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else (
        Path(__file__).resolve().parents[1] / "frontend" / "src" / "filetypes.js"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
